FROM python:3.7-alpine3.9

COPY ./Pipfile /
COPY ./Pipfile.lock /

RUN apk update && apk add libpq

RUN apk add --no-cache --virtual .build-deps \
    gcc \
    python3-dev \
    musl-dev \
    postgresql-dev \
    libpq \
    wkhtmltopdf \
    && pip3 install --no-cache-dir pipenv \
    && pipenv install --deploy --system \
    && apk del --no-cache .build-deps

ADD . /usr/src/app
WORKDIR /usr/src/app

CMD ["gunicorn", "src.run:app","--bind",  "0.0.0.0:8000"]
